#!/bin/bash

ROOT="/btrfs-snapshots"
SNAPSHOT_SEND_KEY=~/.snapshot-tools-send-key

function setup() {
	if [ ! -d "$ROOT/$(hostname)" ]; then
		echo "Creating local root $ROOT/$(hostname)"
		mkdir -p "$ROOT"/"$(hostname)"
	fi
	if [ ! -L "$ROOT/LOCAL" ]; then
		echo "Linking LOCAL into $ROOT"
		ln -s "$(hostname)" "$ROOT/LOCAL"
	fi
	if [ ! -e "$SNAPSHOT_SEND_KEY" ]; then
		echo "Generating our send-key"
		ssh-keygen -t rsa -N '' -C "snapshot-tools-sender-$(hostname)" -f "$SNAPSHOT_SEND_KEY"
	fi
}

function setup_ssh() {
	hostname="$1"
	set -x
	[ -e "$SNAPSHOT_SEND_KEY".pub ] || exit 1
	sed 's|^|command="/root/snapshot-tools/btrfs-recv-only" |' "$SNAPSHOT_SEND_KEY".pub | ssh "$hostname" "mkdir -p ~/snapshot-tools; umask 077; mkdir -p ~/.ssh; grep -q 'snapshot-tools-sender-$(hostname)$' ~/.ssh/authorized_keys 2> /dev/null || cat >> .ssh/authorized_keys"
	scp -r /root/snapshot-tools/btrfs-* "$hostname":snapshot-tools
}

function dir_to_subvolume() {
	# You can't use this on /.
	# You don't need to, either.
	dirname="$1"
	mv "$dirname"{,-tmp}
	btrfs subvolume create "$dirname"
	mv /"$d"-tmp/{,.}* /"$d" || true # We'll catch errors when we try to remove, anyway
	rmdir /"$d"-tmp
}

function setup_dir() {
	dirname="$1"
	encoded="$(encode "$dirname")"
	mkdir "$ROOT/LOCAL/$encoded"
}

function all_hosts() {
	(
		cd "$ROOT";
		for hostroot in *; do
			if [ -d "$hostroot" ] && [ ! -L "$hostroot" ]; then
				echo "$hostroot"
			fi
		done
	)
}

function default_push_hosts() {
	if [ -e "$ROOT"/default-push-hosts ]; then
		cat "$ROOT"/default-push-hosts
	fi
}

function dirs_on_host() {
	host="$1"
	(
		cd "$ROOT/$host"
		for dir in *; do
			echo "$dir"
		done
	)
}
		
function cleanup_all() {
	all_hosts | while read host; do
		dirs_on_host "$host" | while read dir; do
			cleanup_dir "$ROOT/$host/$dir"
		done
	done
}

function cleanup_dir() {
	btrfs-cleanup-candidates $1 | while read DIRNAME; do
		# TODO check it's not the latest for some host.
		# We need to keep those!
		echo "DELETING $DIRNAME"
		btrfs subvolume delete "$DIRNAME"
	done
}

function push_all() {
	dirs_on_host LOCAL | while read encoded; do
		snap "$(decode "$encoded")"
		send_dir "$encoded"
	done
}

function decode() {
	echo "$1" | tr _ /
}

function encode() {
	echo "$1" | tr / _
}

function snap_all() {
	dirs_on_host LOCAL | while read encoded; do
		snap "$(decode "$encoded")"
	done
}

function snap() {
	dirname="$1"
	encoded="$(encode "$dirname")"
	snaproot="$ROOT/LOCAL/$encoded"
	snapname="$snaproot"/"$(date +%Y%m%d-%H%M%S)"
	btrfs subvolume snapshot -r "$dirname" "$snapname"
}

function latest_snap() {
	ls "$ROOT/LOCAL/$1" | grep -v '^CURRENT' | tail -n 1
}

function hosts_for_snapdir() {
	(
		dirname="$1"
		cd "$ROOT/LOCAL/$dirname"
		for I in CURRENT-*; do
			echo "${I#CURRENT-}"
		done
	)
}

function send_all() {
	host="$1"
	dirs_on_host LOCAL | while read encoded; do
		send_dir_host "$encoded" "$host"
	done
}

function send_dir() {
	encoded="$1"
	hosts_for_snapdir "$encoded" | while read host; do
		send_dir_host "$encoded" "$host"
	done
}

function send_dir_defaults() {
	encoded="$1"
	default_push_hosts | while read host; do
		send_dir_host "$encoded" "$host"
	done
}

function add_default_push_host() {
	host="$1"
	grep -v "^$host$" "$ROOT"/default-send-hosts > "$ROOT/default-send-hosts.1"
	echo "$host" >> "$ROOT/default-send-hosts.1"
	mv "$ROOT/default-send-hosts"{.1,}
	dirs_on_host LOCAL | while read encoded; do
		send_dir_host "$encoded" "$host"
	done
}

function ssh_btrfs_send () {
	host="$1"
	encoded="$2"
	SSH_AUTH_SOCK= ssh -o 'Compression yes' -i "$SNAPSHOT_SEND_KEY" root@"$host" receive "$encoded"
}

function send_dir_host() {
	encoded="$1"
	host="$2"
	snapdir="$ROOT/LOCAL/$encoded"
	current="$(latest_snap "$encoded")"
	last_success_file="$snapdir/CURRENT-$host"
	if (
		if [ -e "$last_success_file" ]; then
			# Send a diff
			last_success="$(readlink "$snapdir/CURRENT-$host")"
			if [ "$last_success" != "$current" ]; then
				btrfs send -p "$snapdir/$last_success" "$snapdir/$current" | ssh_btrfs_send "$host" "$encoded"
			else
				false
			fi
		else
			# Send a full snapshot
			btrfs send "$snapdir/$current" | ssh_btrfs_send "$host" "$encoded"
		fi
	); then
		ln -nfs "$current" "$last_success_file"
	fi
}
