#!/bin/sh

valid_host="$(echo "$SSH_CLIENT" | cut -d' ' -f1 | xargs host | grep 'domain name pointer' | cut -d' ' -f5 | cut -d. -f1)"
case "$SSH_ORIGINAL_COMMAND" in
	"btrfs receive /btrfs-snapshots/$valid_host"/*_*)
		host="$(echo "$SSH_ORIGINAL_COMMAND" | sed 's|^[^/]*/btrfs-snapshots/\([^/]*\)/.*|\1|')".bucko.me.uk
		exec $SSH_ORIGINAL_COMMAND
		;;
	*)
		echo "$0: Invalid command for $valid_host: $SSH_ORIGINAL_COMMAND"
		exit 1
		;;
esac
